type lolly {
  flavourTop: String!
  flavourMiddle: String!
  flavourBottom: String!
  recipientName: String!
  message: String!
  senderName: String!
  lollyPath: String!
}

type Query {
  allLollies: [lolly!]!
}